### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by stancl** [shivammathur/node-docker#10]
Hi, is there a timeline for PHP 8.2 support in this repo? I noticed that it's supported in setup-php but this docker image seems to be limited to 8.1.

Thanks!

**Comment by shivammathur** [comment]
Added in https://github.com/shivammathur/node-docker/commit/c365d5d8707ce9fd48c6d4f222e514c02b1846d2

**Comment by stancl** [comment]
Thanks ❤️
