### ISSUE TITLE
Are you open for an alpine variant ?

### ISSUE THREAD

**Issue by williamdes** [shivammathur/node-docker#4]
Alpine images are very slim, what about having an alpine variant ?
Would that be cool for alpine runners ?

**Comment by shivammathur** [comment]
`setup-php` currently only supports `Ubuntu`.

These images have `slim` variants which are just around 50 MB.
https://github.com/shivammathur/node-docker#focal-slim-2004-slim

The caveat is that, `slim` variants do not have PHP installed and when used with `act`, PHP will be installed on each run.
So, I would recommend using the non slim images with act as the image downloads once and then your local testing is faster.

**Comment by williamdes** [comment]
Okay, thanks for letting me know
