### ISSUE TITLE
Issues with PHP 8 PECL extensions when running locally

### ISSUE THREAD

**Issue by rodolfoberrios** [shivammathur/node-docker#5]
**Describe the bug**
I'm having issues testing locally on Ubuntu 20.04 with `act -P ubuntu-latest=shivammathur/node:latest` (including other tags)

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest`

**PHP versions**
`8.0`

**To Reproduce**

Clone this repo: https://github.com/rodolfoberrios/setup-php-test

Run [nektos/act](https://github.com/nektos/act):

`act -P ubuntu-latest=shivammathur/node:latest -W .github/workflows/v2-php8.yml`

**Expected behavior**

It should allow to local test the github action just like running it from github.

**Screenshots/Logs**

```sh
❯ act -P ubuntu-latest=shivammathur/node:latest -W .github/workflows/v2-php8.yml
[PHP 8 no xdebug/build] 🚀  Start image=shivammathur/node:latest
[PHP 8 no xdebug/build]   🐳  docker run image=shivammathur/node:latest entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[PHP 8 no xdebug/build]   🐳  docker cp src=/home/rodolfo/git/rodolfoberrios/setup-php-test/. dst=/github/workspace
[PHP 8 no xdebug/build] ⭐  Run Checkout
[PHP 8 no xdebug/build]   ✅  Success - Checkout
[PHP 8 no xdebug/build] ⭐  Run Setup PHP Action
[PHP 8 no xdebug/build]   ☁  git clone 'https://github.com/shivammathur/setup-php' # ref=v2
[PHP 8 no xdebug/build]   🐳  docker cp src=/home/rodolfo/.cache/act/shivammathur-setup-php@v2 dst=/actions/
| [command]/bin/bash /opt/hostedtoolcache/linux.sh 8.0 /actions/shivammathur-setup-php@v2/dist
| 
| ==> Setup PHP
| ✓ PHP Found PHP 8.0.0
| 
| ==> Setup Tools
| ✓ composer Added composer 2.0.8
[PHP 8 no xdebug/build]   ❗  ::error::The process '/bin/bash' failed with exit code null
[PHP 8 no xdebug/build]   ❌  Failure - Setup PHP Action
Error: exit with `FAILURE`: 1
```

**Additional context**

I have a repo where the action executes successfully at GitHub, but in local [only this workflow](https://github.com/rodolfoberrios/setup-php-test/blob/main/.github/workflows/v2-php8-pecl-ds.yml) is working for me, the one that explicit install pear.

I tested this in two different Ubuntu 20.04 machines, I haven't tested in other OS at this time. I also tested tagging `v1` (old syntax) and it works as expected.

**Are you willing to submit a PR?**

Not sure, I still don't have a clue on where's the issue.

**Comment by rodolfoberrios** [comment]
Hi, I've updated the docker image following your instructions:

```
docker pull shivammathur/node:latest
```

And now [ds](https://github.com/rodolfoberrios/setup-php-test/runs/1577925862?check_suite_focus=true#step:3:14) works.

I've detected that [imagick](https://github.com/rodolfoberrios/setup-php-test/runs/1578071475?check_suite_focus=true) is also giving issues. I tested [with](https://github.com/rodolfoberrios/setup-php-test/runs/1578071418?check_suite_focus=true) and without `imagemagick`.

**Comment by shivammathur** [comment]
Fixed the pecl extensions issue in https://github.com/shivammathur/node-docker/commit/ee664c732d180b91123983d61693985e3017defb
Fixed imagick in https://github.com/shivammathur/setup-php/commit/b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
