### ISSUE TITLE
Compatibility with Node 16

### ISSUE THREAD

**Issue by CristianHG2** [shivammathur/node-docker#8]
**Describe the feature**
Currently, this Docker image supports Node 14 out of the box, however, tools like [shivammathur/cache-extensions](https://github.com/shivammathur/cache-extensions) require Node 16 support. This disables a developer's ability to test a workflow when using tools like `act` with this container image.

**Version**
- [X] I have checked that the feature is missing in the latest version.

**Underlying issue**
Compatibility with other useful packages that might require support for a later version of node.

**Describe alternatives**
Naturally, one can simply set up Node 16 either on a separate container image or add a workflow step to do it on this image. Just thought it would be a convenient capability to have.

**Additional context**
Unless I'm missing a step, it looks like `act`'s default `ubuntu-latest` image is either missing the correct repositories or has another issue that stops PHP extensions from installing properly. Trying to run a workflow step that uses `cache-extensions` when using this image fails the build.

**Are you willing to submit a PR?**
Yes

**Comment by shivammathur** [comment]
node16 support has been added to `nektos/act` in https://github.com/nektos/act/pull/922, you can fetch the build from the [artifacts in the PR](https://github.com/nektos/act/actions/runs/1612738618) or wait for the next release of act.

There is no node 16 specific code in `shivammathur/cache-extensions`, so it should work fine with the node on the images, I will upgrade it to 16 eventually.

You might face another issue though as `actions/cache` and `shivammathur/cache-extensions` are not supported on act and requires adding `if: ${{ !env.ACT }}` to these steps.
https://github.com/nektos/act/issues/329

**Comment by CristianHG2** [comment]
> node16 support has been added to `nektos/act` in [nektos/act#922](https://github.com/nektos/act/pull/922), you can fetch the build from the [artifacts in the PR](https://github.com/nektos/act/actions/runs/1612738618) or wait for the next release of act.
> 
> There is no node 16 specific code in `shivammathur/cache-extensions`, so it should work fine with the node on the images, I will upgrade it to 16 eventually.
> 
> You might face another issue though as `actions/cache` and `shivammathur/cache-extensions` are not supported on act and requires adding `if: ${{ !env.ACT }}` to these steps. [nektos/act#329](https://github.com/nektos/act/issues/329)

Thank you, I will just disable the step then when running local builds then. Just for reference, this is the error I received when trying to run the workflow on act with the `shivammathur/cache-extensions` action:

`Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16`
